# Generated by Django 6.0.5 on 2026-05-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=32, verbose_name='رمز عبور')),
                ('birthdate', models.DateField(verbose_name='تاریخ تولد')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(verbose_name='شماره تلفن')),
                ('profile', models.ImageField(default='avatar.jpg', upload_to='profile.pictures', verbose_name='پروفایل')),
                ('country', models.CharField(choices=[('iran', 'ایران'), ('usa', 'آمریکا')], default='iran', max_length=60, verbose_name='کشور')),
                ('is_private', models.BooleanField(default=False, verbose_name='آیا خصوصی باشد')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('creat_at', models.DateTimeField(verbose_name='زمان ساخت')),
                ('visible', models.BooleanField(default=False, verbose_name='قابل مشاهده')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا پاک شده')),
                ('subject', models.CharField(choices=[('1', 'ورزشی'), ('2', 'شبکه اجتماعی')], default='1', max_length=1, verbose_name='موضوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
    ]
