# Generated by Django 6.0.5 on 2026-05-27 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('visible', models.BooleanField(default=False, verbose_name='قابل مشاهده')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا پاک شده')),
                ('subject', models.CharField(choices=[('1', 'ورزشی'), ('2', 'شبکه اجتماعی')], default='1', max_length=1, verbose_name='موضوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
    ]
